import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:foodplan/data/repository/ingredient_repository.dart';
import 'package:foodplan/data/repository/recipe_repository.dart';
import 'package:foodplan/domain/model/ingredient.dart';
import 'package:foodplan/domain/model/recipe.dart';

class DatabaseSeeder {
  DatabaseSeeder({
    required IngredientRepository ingredientRepository,
    required RecipeRepository recipeRepository,
  })  : _ingredientRepository = ingredientRepository,
        _recipeRepository = recipeRepository;

  final IngredientRepository _ingredientRepository;
  final RecipeRepository _recipeRepository;

  /// Seeds the shared Firestore collections exactly once — checked directly
  /// against Firestore (not the local cache, which starts empty on fresh install).
  Future<void> seedIfEmpty() async {
    final snap = await FirebaseFirestore.instance
        .collection('ingredients')
        .limit(1)
        .get();
    if (snap.docs.isNotEmpty) return;
    await _seedIngredients();
    await _seedRecipes();
    // Meal plan seeding is skipped — generated by the optimizer.
  }

  // ── Ingredients ───────────────────────────────────────────────────────────

  Future<void> _seedIngredients() async {
    final all = [
      // Protein – kyckling
      _i('ing_kyckling_kronfagel', 'Kycklingbröstfilé (Kronfågel)',
          IngredientCategory.meat, 90.0, 19.0, 2.0, 0.0,
          IngredientSource.label),
      _i('ing_kyckling_lindstroms', 'Kyckling (Lindströms)',
          IngredientCategory.meat, 104.0, 22.0, 2.0, 0.0,
          IngredientSource.label),
      _i('ing_kyckling_guldfagel', 'Kycklingbröstfilé (Guldfågel)',
          IngredientCategory.meat, 120.0, 23.0, 2.0, 0.0,
          IngredientSource.label),
      // Protein – fisk
      _i('ing_lax', 'Lax (rå)', IngredientCategory.fish, 188.0, 20.0, 13.0,
          0.0, IngredientSource.livsmedelsverket),
      _i('ing_tonfisk', 'Tonfisk i vatten (ICA)', IngredientCategory.fish,
          110.0, 24.0, 1.0, 0.0, IngredientSource.label),
      // Protein – kött
      _i('ing_nottfars_12', 'Nöttfärs 12% (rå)', IngredientCategory.meat,
          184.0, 19.0, 12.0, 0.0, IngredientSource.label),
      _i('ing_nottfars_5', 'Nöttfärs 5% (rå)', IngredientCategory.meat,
          107.0, 21.0, 3.0, 0.0, IngredientSource.calculated),
      _i('ing_biff_ryggbiff', 'Biff ryggbiff nöt', IngredientCategory.meat,
          120.0, 22.0, 4.0, 0.0, IngredientSource.livsmedelsverket),
      // Protein – ägg
      _i('ing_agg', 'Ägg', IngredientCategory.dairyEggs, 143.0, 13.0, 10.0,
          0.0, IngredientSource.livsmedelsverket),
      // Mejeri
      _i('ing_creme_fraiche', 'Lätt crème fraîche (ICA)',
          IngredientCategory.dairyEggs, 150.0, 3.0, 7.0, 4.0,
          IngredientSource.label),
      _i('ing_matlagningsgradde', 'Matlagningsgrädde 15%',
          IngredientCategory.dairyEggs, 160.0, 3.0, 15.0, 4.0,
          IngredientSource.label),
      _i('ing_graddfil', 'Gräddfil', IngredientCategory.dairyEggs, 138.0,
          3.0, 12.0, 4.0, IngredientSource.label),
      _i('ing_mozzarella', 'Mozzarella (Arla)', IngredientCategory.dairyEggs,
          303.0, 27.0, 23.0, 0.0, IngredientSource.label),
      _i('ing_arla_ost', 'Arla Köket mager ost 12%',
          IngredientCategory.dairyEggs, 243.0, 30.0, 13.0, 0.0,
          IngredientSource.label),
      _i('ing_mjolk_laktos', 'Mjölk laktosfri 1.5%',
          IngredientCategory.dairyEggs, 45.0, 4.0, 2.0, 5.0,
          IngredientSource.label),
      _i('ing_smor', 'Smör (Arla)', IngredientCategory.dairyEggs, 714.0, 1.0,
          80.0, 0.0, IngredientSource.label),
      _i('ing_tzatsiki', 'Tzatsiki (Fontana)', IngredientCategory.dairyEggs,
          131.0, 5.4, 10.1, 4.5, IngredientSource.label),
      _i('ing_smelteost', 'Smelteost cheddar (Country Cow)',
          IngredientCategory.dairyEggs, 308.0, 10.0, 25.0, 4.0,
          IngredientSource.label),
      _i('ing_grekghurt_larsa', 'Grekisk Yoghurt 0% (Larsa)',
          IngredientCategory.dairyEggs, 59.0, 10.0, 0.0, 4.0,
          IngredientSource.label),
      _i('ing_grekghurt_arla', 'Grekisk Yoghurt 0.2% (Arla)',
          IngredientCategory.dairyEggs, 60.0, 11.0, 0.0, 4.0,
          IngredientSource.label),
      // Spannmål – torrt
      _i('ing_jasminris', 'Jasminris (okokt)', IngredientCategory.grains,
          349.0, 7.0, 1.0, 78.0, IngredientSource.label),
      _i('ing_bovete', 'Bovete Ekologiskt (Garant, torrt)',
          IngredientCategory.grains, 356.0, 8.0, 1.0, 74.0,
          IngredientSource.label),
      _i('ing_fullkornspasta', 'Fullkornspasta (Garant, torr)',
          IngredientCategory.grains, 350.0, 12.0, 2.0, 67.0,
          IngredientSource.label),
      _i('ing_cavatappi', 'Cavatappi pasta (De Cecco, torr)',
          IngredientCategory.grains, 358.0, 12.0, 2.0, 71.0,
          IngredientSource.label),
      _i('ing_basmatiris', 'Basmatiris vit (torrt)', IngredientCategory.grains,
          365.0, 7.0, 1.0, 80.0, IngredientSource.label),
      _i('ing_japansktris', 'Japanskt ris (okokt)', IngredientCategory.grains,
          355.0, 8.0, 1.0, 77.0, IngredientSource.label),
      // Grönsaker
      _i('ing_potatis', 'Potatis', IngredientCategory.fruitVeg, 79.0, 2.0,
          0.0, 17.0, IngredientSource.livsmedelsverket),
      _i('ing_gullok', 'Gullök', IngredientCategory.fruitVeg, 32.0, 2.0, 0.0,
          7.0, IngredientSource.label),
      _i('ing_krossade_tomater', 'Krossade tomater', IngredientCategory.fruitVeg,
          22.0, 1.0, 0.0, 4.0, IngredientSource.label),
      _i('ing_gurka', 'Gurka', IngredientCategory.fruitVeg, 12.0, 1.0, 0.0,
          2.0, IngredientSource.label),
      _i('ing_rodlok', 'Rödlök', IngredientCategory.fruitVeg, 40.0, 1.0, 0.0,
          9.0, IngredientSource.label),
      _i('ing_paprika', 'Paprika', IngredientCategory.fruitVeg, 31.0, 1.0,
          0.0, 6.0, IngredientSource.label),
      _i('ing_vitlok', 'Vitlök', IngredientCategory.fruitVeg, 135.0, 6.0, 1.0,
          28.0, IngredientSource.label),
      _i('ing_basilika', 'Basilika (färsk)', IngredientCategory.fruitVeg,
          23.0, 3.0, 1.0, 1.0, IngredientSource.label),
      _i('ing_morotter', 'Morötter', IngredientCategory.fruitVeg, 38.0, 1.0,
          0.0, 8.0, IngredientSource.label),
      _i('ing_salladslok', 'Salladslök', IngredientCategory.fruitVeg, 30.0,
          2.0, 0.0, 5.0, IngredientSource.label),
      _i('ing_dill', 'Dill (färsk)', IngredientCategory.fruitVeg, 43.0, 3.0,
          1.0, 4.0, IngredientSource.label),
      // Frukt
      _i('ing_banan', 'Banan', IngredientCategory.fruitVeg, 83.0, 1.0, 0.0,
          19.0, IngredientSource.label),
      // Frö/nötter
      _i('ing_sesamfro', 'Sesamfrö (GoGreen)', IngredientCategory.nuts, 600.0,
          20.0, 53.0, 12.0, IngredientSource.label),
      // Fryst
      _i('ing_frysta_artor', 'Frysta ärtor', IngredientCategory.frozen, 73.0,
          5.0, 0.0, 12.0, IngredientSource.label),
      // Bröd
      _i('ing_tortilla', 'Tortilla Large (ICA)', IngredientCategory.breadBakery,
          302.0, 8.3, 4.9, 55.0, IngredientSource.label),
      _i('ing_burgarbrod', 'Potato Burger Bun (Korvbröds Bagarn)',
          IngredientCategory.breadBakery, 280.0, 9.0, 5.0, 50.0,
          IngredientSource.label),
      // Flingor/müsli
      _i('ing_musli_gold', 'Gold BERRIES musli', IngredientCategory.dryGoods,
          422.0, 10.0, 16.0, 55.0, IngredientSource.label),
      _i('ing_musli_frebaco', 'Frebaco Müsli (Persika Hallon)',
          IngredientCategory.dryGoods, 320.0, 12.0, 4.0, 60.0,
          IngredientSource.label),
      // Buljong
      _i('ing_kalvbuljong', 'Kalvbuljong (Knorr)', IngredientCategory.oilsSauces,
          170.0, 4.0, 0.0, 38.0, IngredientSource.label),
      _i('ing_gronsaksbuljong', 'Grönsaksbuljong', IngredientCategory.oilsSauces,
          10.0, 1.0, 0.0, 2.0, IngredientSource.label),
      // Sås
      _i('ing_kinesisk_soja', 'Kinesisk Soja', IngredientCategory.oilsSauces,
          50.0, 5.0, 0.0, 8.0, IngredientSource.label),
      _i('ing_ostronsas', 'Ostronsås', IngredientCategory.oilsSauces, 51.0,
          2.0, 0.0, 13.0, IngredientSource.label),
      _i('ing_dijonsenap', 'Dijonsenap', IngredientCategory.oilsSauces, 70.0,
          4.0, 4.0, 5.0, IngredientSource.label),
      // Fett
      _i('ing_rapsolja', 'Rapsolja', IngredientCategory.oilsSauces, 900.0,
          0.0, 100.0, 0.0, IngredientSource.label),
      _i('ing_sesamolja', 'Sesamolja', IngredientCategory.oilsSauces, 884.0,
          0.0, 100.0, 0.0, IngredientSource.label),
      // Konserv
      _i('ing_tomatpure', 'Tomatpuré', IngredientCategory.canned, 82.0, 4.0,
          0.0, 16.0, IngredientSource.label),
      _i('ing_gochujang', 'Gochujang', IngredientCategory.canned, 200.0, 5.0,
          5.0, 35.0, IngredientSource.label),
    ];
    await _ingredientRepository.saveIngredients(all);
  }

  // ── Recipes ───────────────────────────────────────────────────────────────

  Future<void> _seedRecipes() async {
    // 1. Bovete kyckling — Lunch/Dinner
    await _recipeRepository.saveRecipe(Recipe(
      id: 'recipe_bovete_kyckling',
      name: 'Buckwheat chicken',
      type: RecipeType.meal,
      mealCategories: {MealCategory.lunch, MealCategory.dinner},
      ingredients: [
        _ri('ing_bovete', 85.0),
        _ri('ing_kyckling_kronfagel', 180.0),
        _ri('ing_tzatsiki', 45.0),
      ],
      steps: const [
        'Cook buckwheat according to package instructions. Set aside.',
        'Season chicken breast with salt and pepper. Grill or pan-fry 6–8 minutes per side until cooked through.',
        'Slice chicken and serve over buckwheat. Top with tzatsiki.',
      ],
      notes: 'Tweaked: chicken 150g → 180g. Target: ~580 kcal / ~52g P',
    ));

    // 2. Curry kyckling — Lunch/Dinner
    await _recipeRepository.saveRecipe(Recipe(
      id: 'recipe_curry_kyckling',
      name: 'Curry chicken',
      type: RecipeType.meal,
      mealCategories: {MealCategory.lunch, MealCategory.dinner},
      ingredients: [
        _ri('ing_jasminris', 60.0),
        _ri('ing_matlagningsgradde', 50.0),
        _ri('ing_creme_fraiche', 50.0),
        _ri('ing_kyckling_kronfagel', 200.0),
        _ri('ing_kinesisk_soja', 4.0),
        _ri('ing_gronsaksbuljong', 50.0),
        _ri('ing_gullok', 100.0),
        _ri('ing_vitlok', 10.0),
      ],
      steps: const [
        'Cook jasmine rice according to package instructions.',
        'Sauté onion and garlic in a pan until soft.',
        'Add chicken and cook through. Add soy sauce.',
        'Stir in crème fraîche and cooking cream. Simmer 5 minutes.',
        'Add vegetable stock and season to taste. Serve over rice.',
      ],
      notes:
          'Tweaked: rice 100g → 60g, chicken 100 → 200g. Target: ~620 kcal / ~57g P',
    ));

    // 3. Köttfärs & pasta — Lunch/Dinner
    await _recipeRepository.saveRecipe(Recipe(
      id: 'recipe_kottfars_pasta',
      name: 'Minced beef & pasta',
      type: RecipeType.meal,
      mealCategories: {MealCategory.lunch, MealCategory.dinner},
      ingredients: [
        _ri('ing_nottfars_12', 220.0),
        _ri('ing_fullkornspasta', 50.0),
        _ri('ing_krossade_tomater', 50.0),
        _ri('ing_tomatpure', 30.0),
        _ri('ing_gochujang', 30.0),
        _ri('ing_gullok', 100.0),
      ],
      steps: const [
        'Cook pasta according to package instructions.',
        'Fry onion until soft. Add minced beef and brown thoroughly.',
        'Add tomato purée, crushed tomatoes and gochujang. Stir well.',
        'Simmer 10–15 minutes. Season to taste.',
        'Serve beef sauce over pasta.',
      ],
      notes: 'Tweaked: beef 150g → 220g. Target: ~650 kcal / ~58g P',
    ));

    // 4. Makaronigratäng — Lunch/Dinner
    await _recipeRepository.saveRecipe(Recipe(
      id: 'recipe_makaronigratang',
      name: 'Macaroni gratin',
      type: RecipeType.meal,
      mealCategories: {MealCategory.lunch, MealCategory.dinner},
      ingredients: [
        _ri('ing_nottfars_12', 170.0),
        _ri('ing_agg', 55.0),
        _ri('ing_mjolk_laktos', 50.0),
        _ri('ing_krossade_tomater', 50.0),
        _ri('ing_arla_ost', 30.0),
        _ri('ing_cavatappi', 50.0),
        _ri('ing_gullok', 100.0),
        _ri('ing_basilika', 15.0),
      ],
      steps: const [
        'Cook pasta until al dente. Drain and set aside.',
        'Fry onion and minced beef. Season with salt and pepper.',
        'Add crushed tomatoes and simmer 5 minutes.',
        'Mix egg and milk in a bowl.',
        'Layer pasta, beef and tomato in an oven dish. Pour egg mixture over. Top with grated cheese and basil.',
        'Bake at 200°C for 25–30 minutes until golden.',
      ],
      notes: 'Tweaked: beef 150g → 170g. Target: ~700 kcal / ~60g P',
    ));

    // 5. Fried rice — Lunch/Dinner
    await _recipeRepository.saveRecipe(Recipe(
      id: 'recipe_fried_rice',
      name: 'Fried rice',
      type: RecipeType.meal,
      mealCategories: {MealCategory.lunch, MealCategory.dinner},
      ingredients: [
        _ri('ing_basmatiris', 70.0),
        _ri('ing_kyckling_kronfagel', 180.0),
        _ri('ing_agg', 110.0),
        _ri('ing_ostronsas', 30.0),
        _ri('ing_sesamolja', 5.0),
        _ri('ing_frysta_artor', 100.0),
        _ri('ing_morotter', 100.0),
        _ri('ing_salladslok', 30.0),
      ],
      steps: const [
        'Cook and cool rice (ideally day-old rice works best).',
        'Cook chicken in a hot wok until done. Set aside.',
        'Scramble eggs in the same wok. Push to the side.',
        'Add rice, peas, carrot and chicken. Stir-fry on high heat 3–4 minutes.',
        'Add oyster sauce and sesame oil. Toss well.',
        'Top with sliced spring onion and serve.',
      ],
      notes:
          'Tweaked: rice 100g → 70g, chicken 125g → 180g, eggs 1 → 2. Target: ~740 kcal / ~76g P',
    ));

    // 6. Tonfisk m. ris — Dinner
    await _recipeRepository.saveRecipe(Recipe(
      id: 'recipe_tonfisk_ris',
      name: 'Tuna with rice',
      type: RecipeType.meal,
      mealCategories: {MealCategory.dinner},
      ingredients: [
        _ri('ing_creme_fraiche', 150.0),
        _ri('ing_sesamfro', 5.0),
        _ri('ing_tonfisk', 180.0),
        _ri('ing_jasminris', 50.0),
        _ri('ing_gurka', 150.0),
        _ri('ing_rodlok', 80.0),
      ],
      steps: const [
        'Cook jasmine rice according to package instructions.',
        'Mix tuna with crème fraîche and sesame seeds.',
        'Slice cucumber and red onion.',
        'Serve tuna mix over rice with cucumber and red onion on the side.',
      ],
      notes:
          'Removed Hellman\'s, more crème fraîche & tuna. Target: ~560 kcal / ~60g P',
    ));

    // 7. Quesadillas — Dinner
    await _recipeRepository.saveRecipe(Recipe(
      id: 'recipe_quesadillas',
      name: 'Quesadillas',
      type: RecipeType.meal,
      mealCategories: {MealCategory.dinner},
      ingredients: [
        _ri('ing_tortilla', 93.0),
        _ri('ing_mozzarella', 30.0),
        _ri('ing_kyckling_kronfagel', 250.0),
        _ri('ing_gullok', 100.0),
        _ri('ing_paprika', 150.0),
        _ri('ing_tomatpure', 30.0),
      ],
      steps: const [
        'Season and cook chicken until done. Slice into strips.',
        'Sauté onion and pepper until soft.',
        'Spread tomato purée on tortilla. Add chicken, vegetables and mozzarella.',
        'Fold tortilla and pan-fry 2–3 minutes per side until golden and cheese is melted.',
      ],
      notes:
          'Tweaked: 1 → 1.5 tortilla, chicken 200g → 250g. Target: ~800 kcal / ~82g P',
    ));

    // 8. Union burger — Dinner
    await _recipeRepository.saveRecipe(Recipe(
      id: 'recipe_union_burger',
      name: 'Union burger',
      type: RecipeType.meal,
      mealCategories: {MealCategory.dinner},
      ingredients: [
        _ri('ing_gullok', 50.0),
        _ri('ing_nottfars_12', 200.0),
        _ri('ing_smelteost', 40.0),
        _ri('ing_burgarbrod', 70.0),
        _ri('ing_agg', 55.0),
      ],
      steps: const [
        'Mix minced beef with egg, salt and pepper. Form into a patty.',
        'Fry onion until golden and caramelised.',
        'Cook burger patty in a hot pan 3–4 minutes per side.',
        'Top with melted cheddar during the last minute.',
        'Serve in burger bun with caramelised onion.',
      ],
      notes: 'Tweaked: 12% beef 200g, added egg. Target: ~782 kcal / ~57g P',
    ));

    // 9. Biffstroganoff — Dinner
    await _recipeRepository.saveRecipe(Recipe(
      id: 'recipe_biffstroganoff',
      name: 'Beef stroganoff',
      type: RecipeType.meal,
      mealCategories: {MealCategory.dinner},
      ingredients: [
        _ri('ing_japansktris', 60.0),
        _ri('ing_biff_ryggbiff', 230.0),
        _ri('ing_graddfil', 50.0),
        _ri('ing_matlagningsgradde', 25.0),
        _ri('ing_kalvbuljong', 50.0),
        _ri('ing_smor', 7.0),
      ],
      steps: const [
        'Cook Japanese rice according to package instructions.',
        'Slice beef into thin strips. Season with salt and pepper.',
        'Fry beef quickly in butter over high heat. Set aside.',
        'Add stock to the pan and reduce slightly.',
        'Stir in sour cream and cooking cream. Simmer 5 minutes.',
        'Return beef to the sauce. Serve over rice.',
      ],
      notes:
          'Tweaked: rice 80g → 60g, beef 200g → 230g. Target: ~745 kcal / ~61g P',
    ));

    // 10. Lax & potatis — Dinner
    await _recipeRepository.saveRecipe(Recipe(
      id: 'recipe_lax_potatis',
      name: 'Salmon & potatoes',
      type: RecipeType.meal,
      mealCategories: {MealCategory.dinner},
      ingredients: [
        _ri('ing_lax', 230.0),
        _ri('ing_potatis', 220.0),
        _ri('ing_creme_fraiche', 100.0),
        _ri('ing_dijonsenap', 5.0),
        _ri('ing_dill', 15.0),
      ],
      steps: const [
        'Boil potatoes until tender, about 20 minutes.',
        'Season salmon and bake or pan-fry 4–5 minutes per side.',
        'Mix crème fraîche with Dijon mustard and chopped dill for the sauce.',
        'Serve salmon and potatoes with dill sauce.',
      ],
      notes:
          'Tweaked: salmon 150g → 230g, potatoes 300g → 220g, added dill sauce. Target: ~740 kcal / ~56g P',
    ));

    // 11. Müsli banan grekghurt — Snack
    await _recipeRepository.saveRecipe(Recipe(
      id: 'recipe_musli_snack',
      name: 'Muesli with banana & yoghurt',
      type: RecipeType.meal,
      mealCategories: {MealCategory.snack},
      ingredients: [
        _ri('ing_musli_gold', 35.0),
        _ri('ing_banan', 60.0),
        _ri('ing_grekghurt_larsa', 200.0),
      ],
      steps: const [
        'Add yoghurt to a bowl.',
        'Top with muesli and sliced banana.',
      ],
      notes:
          'Tweaked: muesli 25g → 35g, agave removed. Target: ~285 kcal / ~29g P',
    ));
  }

  // ── Helpers ───────────────────────────────────────────────────────────────

  Ingredient _i(
    String id,
    String name,
    IngredientCategory category,
    double kcal,
    double protein,
    double fat,
    double carbs,
    IngredientSource source,
  ) =>
      Ingredient(
        id: id,
        name: name,
        category: category,
        kcalPer100g: kcal,
        proteinPer100g: protein,
        fatPer100g: fat,
        carbsPer100g: carbs,
        source: source,
      );

  RecipeIngredient _ri(String ingredientId, double grams) =>
      RecipeIngredient(ingredientId: ingredientId, grams: grams);
}
